### ISSUE TITLE
"Download Now" button is obscured when prompted to download new schedule

### ISSUE THREAD

**Issue by nrizzio** [septadev/SEPTA-Android#199]
When I launch the app, I am prompted to download updated schedules. However, I cannot tap on the "Download Now" button because the two other buttons push it out of the view of the screen.

Image:

![dialogue](https://user-images.githubusercontent.com/13669330/43994613-e91b0786-9d6d-11e8-9a0e-0efc57963e34.png)

I believe that this is the method that needs to be adjusted:
https://github.com/septadev/SEPTA-Android/blob/fc7e4d14180b13657e2e02d35c668d8f2380f631/app/src/main/java/org/septa/android/app/database/update/DatabaseUpgradeUtils.java#L132-L185

**Comment by yannick-b** [comment]
hi,

thx for your feedback. We will send it to the dev team for review/fix.

Yannick
________________________________

**Comment by nrizzio** [comment]
This issue was fixed by pull request #200.
