### ISSUE TITLE
Schedule->BSL-> Saturday ->Start Station Fern Rock End Station Spring Garden trip time

### ISSUE THREAD

**Issue by yannick-b** [septadev/SEPTA-Android#41]
Expected Result: Reasonable lengths of trips displayed 
Actual result: Result "2" returns a 1262 Minute route.

**Comment by jhunchar** [comment]
@yannick-b -- I noticed "1" returns a 122 minute route as well. I will look into this.

**Comment by jhunchar** [comment]
PR #96 fixed
