### ISSUE TITLE
Provide RR Alerts on NTA screen:

### ISSUE THREAD

**Issue by yannick-b** [septadev/SEPTA-Android#87]
Add Generic RR alerts and RR specif alerts on NTA screen
![final nta views](https://cloud.githubusercontent.com/assets/2581758/6872837/49af5470-d482-11e4-99f1-618058445732.png)

**Comment by antoinecampbell** [comment]
Issue has been addressed but will be closed when there is actually an alert in the system

**Comment by jhunchar** [comment]
Implemented in v1.3.8
