### ISSUE TITLE
Provide Alerts status on RR schedule route list

### ISSUE THREAD

**Issue by yannick-b** [septadev/SEPTA-Android#88]
Add generic alerts at the top of RR route list in schedule and display route status icon specific to each route
![rr schedule route list](https://cloud.githubusercontent.com/assets/2581758/6872890/abc5fa7e-d482-11e4-9260-bc070ffb5437.png)

**Comment by antoinecampbell** [comment]
Issue has been addressed but will be closed when there is actually an alert in the system

**Comment by jhunchar** [comment]
Implemented in v1.3.8
